### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by foresto** [polarblau/stickySectionHeaders#3]
I'm using Firefox 9, and the headers scroll right by with all the other items.

**Comment by polarblau** [comment]
Thanks for the information. A few questions: I'm assuming Javascript is of course enabled? Are you seeing any JS errors? Are you referring to the demo page or your own implementation? FF9 on which platform — Win, OS X, Linux…? 

— Many thanks for your help!

**Comment by foresto** [comment]
My mistake. Javascript was enabled and I had told NoScript to white-list the site, but it decided to block a script anyway without any indication in the UI.  Here's the relevant message from the javascript console:

[NoScript] Blocking nosniff Javascript served from https://raw.github.com/polarblau/stickySectionHeaders/master/src/jquery.stickysectionheaders.js with wrong type info text/plain, inline and included by http://polarblau.github.com/stickySectionHeaders/

**Comment by polarblau** [comment]
No problem, as long as it works for you.
