### ISSUE TITLE
request nested sticky headers

### ISSUE THREAD

**Issue by paultje1973** [polarblau/stickySectionHeaders#6]
Hi there, your script assumes the UL has a overflow scroll, but i want to implement your script within a website with header/footer, etc. How do i make your script work with the scroll on the window event?

**Comment by polarblau** [comment]
Hello yourself :smirk_cat:
Do I understand correctly: You'd like to programmatically scroll the element for which you're using the plugin? If not, could you give me an example or describe your case a bit more in detail? — Cheers!

**Comment by paultje1973** [comment]
Hey, i fixed it. What my situation was that my sticky headers where inside a div with a header and footer underneat so what i did was:

top        = $this.offset().top - $(window).scrollTop()

to calculate the offset, then:

if (top < offSetSticky + 1) { etc }

and as last:

'top'  : ((height + top) - offSetSticky < headHeight) ? ((headHeight - (top + height)) \* -1) : '',

**Comment by polarblau** [comment]
Good that it works for you!
