### ISSUE TITLE
Github page is broken

### ISSUE THREAD

**Issue by benastan** [polarblau/stickySectionHeaders#7]
You're requesting the JavaScript for the plugin demo from raw.github.com, which has content type `text/plain`. If you want to repair the page, change the url of the library to `https://rawgithub.com/polarblau/stickySectionHeaders/master/src/jquery.stickysectionheaders.js`.

**Comment by polarblau** [comment]
Good catch, thanks. I believe Github had announced this change but I missed to fix the URL so far. — Will be fixed!
